00Readme/API-docs-AirBnB.md
Testing temporary branch creation for features. - esme
=> test-feature branch- esme

backend/routes/api/index.js, backend/routes/index.js
=> give it a quick over view please

backend/app.js
=> check over 

backend/backend/backend/routes/api/index.js, backend/backend/backend/routes/api/session.js, backend/backend/backend/routes/api/users.js, backend/package-lock.json, backend/package.json
=> Add User logout backend endpoint

Github Cheatsheet.md
Added a github cheatsheet to help the team
=> Create Github Cheatsheet.md

backend/app.js, backend/db/migrations/02-review-image.js, backend/db/migrations/03-booking.js, backend/db/migrations/04-review.js, backend/db/migrations/05-spots.js, backend/db/migrations/06-spot-image.js, backend/db/models/booking.js, backend/db/models/review.js, backend/db/models/reviewImage.js, backend/db/models/spot.js, backend/db/models/spotImage.js, backend/package-lock.json
- Users, ReviewImages, Bookings, Reviews, Spots, SpotImages tables were added to migrations and models folders
- Updating as a safe point
- Based table attributes from original db diagram
- Review is needed for naming conventions, camel-casing, and correct data/name verification.
=> added all tables to migrations/ added all tables to models

package.json
=> Scripts to deploy

backend/package.json, package.json
=> moving staged to main

backend/db/models/spot.js
- added spots model with constraints
- no issues
=> spots model

backend/db/migrations/02-spots.js
- added relationships/references to Spots table
- added constraints to Spots table
=> Spots added to migrations

backend/routes/api/index.js, backend/routes/api/reviews.js, backend/routes/api/spots.js
=> routes spots and reviews added

backend/db/migrations/01-user.js, backend/db/models/user.js
- added firstName and lastName to models and migrations folders
=> Users table attributes addition

backend/db/migrations/02-spot.js, backend/db/models/spot.js, backend/db/seeders/02-spot.js, backend/routes/api/spots.js
=> Spot routes

backend/db/migrations/02-spot.js, backend/db/models/spot.js, backend/db/seeders/02-spot.js, backend/routes/api/spots.js
=>  Tweaking bugs

backend/db/migrations/05-review-image.js, backend/db/migrations/06-booking.js, backend/db/models/booking.js, backend/db/models/review.js, backend/db/models/reviewImage.js, backend/db/models/spot.js, backend/db/models/spotImage.js, backend/db/models/user.js, backend/db/seeders/03-spot-images.js, backend/db/seeders/04-review.js, backend/db/seeders/05-review-images.js, backend/db/seeders/06-booking.js, backend/routes/api/spots.js, backend/routes/api/users.js
=> Migrations, seeds, models

backend/db/migrations/02-spot.js, backend/db/models/reviewImage.js, backend/db/models/spot.js, backend/db/seeders/02-spot.js, backend/db/seeders/06-booking.js, backend/routes/api/spots.js
fixed some spot issues. owner should be userId not ownerId
=> Bug for routes fixed

backend/db/models/spotImage.js, backend/db/seeders/02-spot.js, backend/routes/api/review-images.js, backend/routes/api/spots.js, backend/utils/errorHandler.js
=> merged all our changes into 1 branch and fixed various issues

backend/routes/api/index.js, backend/routes/api/review-images.js, backend/routes/api/spots.js
=> Spots mostly running

backend/.env.example, backend/routes/api/bookings.js, backend/routes/api/index.js, backend/routes/api/review-images.js, backend/routes/api/reviews.js, backend/routes/api/session.js, backend/routes/api/users.js
- updating api routes with error handling
=> Added error handling & bookings routes

backend/.env.example, backend/db/seeders/04-review.js, backend/db/seeders/05-review-images.js, backend/db/seeders/06-booking.js, backend/routes/api/bookings.js, backend/routes/api/index.js, backend/routes/api/reviews.js, backend/routes/api/spots.js
=> Getting ready to push to main

backend/routes/api/spots.js
Check over real fast for merge conflicts
=> fixed edit but no time to make it look pretty

backend/routes/api/bookings.js, backend/routes/api/index.js, backend/routes/api/review-images.js, backend/routes/api/reviews.js, backend/routes/api/session.js, backend/routes/api/spots.js, backend/routes/api/users.js, backend/utils/errorHandler.js
=> Staging fix

backend/db/migrations/02-spot.js, backend/db/models/booking.js, backend/db/models/review.js, backend/db/models/spot.js, backend/db/models/user.js, backend/routes/api/users.js
Added a few validations. haven't pushed up everything as I still am working on getting a few to work properly
=> Validations

backend/package.json, backend/routes/api/spots.js, backend/routes/api/users.js
=> Fixed 3 spot routes

backend/db/migrations/03-spot-image.js, backend/db/models/booking.js, backend/db/models/reviewImage.js, backend/db/models/spot.js, backend/db/models/spotImage.js, backend/db/seeders/02-spot.js, backend/db/seeders/04-review.js, backend/routes/api/index.js, backend/routes/api/review-images.js, backend/routes/api/reviews.js, backend/routes/api/spot-images.js, backend/routes/api/spots.js, backend/utils/errorHandler.js
fixed some spots and error handlers
=> fixed some spots up

backend/db/migrations/03-spot-image.js, backend/db/models/spotImage.js, backend/routes/api/bookings.js, backend/routes/api/spot-images.js
=> bookings and spot-image updates

backend/routes/api/spots.js
=> Bookings in Spots fixed

backend/routes/api/bookings.js, backend/routes/api/spots.js
Will work on getting Pages done soon
=> Adjusted an error in bookings

backend/routes/api/spots.js
spots should show page and size only when it's requested in the params
=> added page and size

backend/routes/api/spots.js
offset:size * (page -1) to off set so that it would correlate when moving pages
added functionality of query data
=> fixed off set

backend/routes/api/reviews.js, backend/routes/api/spots.js
=> Staging-fix to main

backend/db/migrations/02-spot.js, backend/routes/api/reviews.js
added as owner to migrations to see if that fixes the issue. also adjusted reviews to hopfully not have any issues.
=> attempting a deployment fix

backend/db/models/booking.js, backend/db/models/review.js, backend/db/models/reviewImage.js, backend/db/models/spot.js, backend/db/models/spotImage.js
=> attempted 2

backend/db/models/review.js, backend/db/seeders/04-review.js, backend/routes/api/reviews.js, backend/routes/api/spots.js, frontend/src/App.jsx, frontend/src/components/AllSpots/AllSpots.css, frontend/src/components/AllSpots/AllSpots.jsx, frontend/src/components/AllSpots/Subcomponents/SpotCard.jsx, frontend/src/components/LoginFormModal/LoginFormModal.jsx, frontend/src/components/Navigation/CreateSpot/CreateSpot.jsx, frontend/src/components/Navigation/ManageSpot/ManageSpot.jsx, frontend/src/components/Navigation/ManageSpot/Subcomponent/DeleteButton.jsx, frontend/src/components/Navigation/ManageSpot/Subcomponent/UserSpotCard.jsx, frontend/src/components/Navigation/Navigation.css, frontend/src/components/Navigation/Navigation.jsx, frontend/src/components/Navigation/ProfileButton.css, frontend/src/components/Navigation/ProfileButton.jsx, frontend/src/components/Navigation/UpdateSpot/UpdateSpot.jsx, frontend/src/components/SignupFormModal/SignupForm.css, frontend/src/components/SpotById/SpotById.css, frontend/src/components/SpotById/SpotById.jsx, frontend/src/components/SpotById/SubComponent/ReviewPopout.css, frontend/src/components/SpotById/SubComponent/ReviewPopout.jsx, frontend/src/components/SpotById/SubComponent/SubReview.jsx, frontend/src/index.css, frontend/src/store/review.js, frontend/src/store/session.js, frontend/src/store/spot.js, frontend/src/store/store.js
This is a lot of a push trying to regulate my pushes now
=> Ch create update
